### ISSUE TITLE
Badge Viewing Activity

### ISSUE THREAD

**Issue by fortnight** [FOSSRIT/lemonade-stand#15]
Our project revolves around making Mozilla Open Badges applicable to the Lemonade Stand game and XO Laptops. XO laptops however, have no way to view Badges without going online.
-> Implement an activity to allow users to view acquired badges
-> Activity can also show what badges are possible to receive and under which conditions
-> Maybe cool graphic with Sash covered in badges acquired (optional)

**Comment by ramstush** [comment]
Made a new activity called Sash that has been stood up on the XO, it just needs code now. Search FOSSRIT for Sash.
