### ISSUE TITLE
Lemonade stand showing up in journal

### ISSUE THREAD

**Issue by fortnight** [FOSSRIT/lemonade-stand#16]
As an activity, Lemonade Stand should show up in the Journal on the XO laptops.
-> Discover a way to have Lemonade Stand showing up in the Journal
-> After discovering why it won't show up in the journal, see if there is a way to save game data to the datastore file.

**Comment by ramstush** [comment]
The Journal automatically makes an entry.  The thing that was blocking Lemonade Stand was a boolean that was set to false in the class params.  Changed that to true and it works.
