### ISSUE TITLE
Negative Effects

### ISSUE THREAD

**Issue by fortnight** [FOSSRIT/lemonade-stand#5]
Negative Effects currently do not affect large numbers of goods.
-> Implement proportional negative effects to counterbalance profits
-->> More sugar attracts more ants
-->> Additional other negative events (optional)
-> Enable the unused code for lemon decay (optional)
-> Have Negative Effects adjust by difficulty

**Comment by ramstush** [comment]
LemonZilla needs adding as well.

**Comment by DAWacker** [comment]
DAWacker also hacking at this.
